# Travis CI
# (C) 2017 Elena Cuoco


env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"



sudo: required

before_install:
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - sudo apt-get install libboost-dev libfftw3-dev
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
compiler:
  - gcc
  - clang

# Build steps
script:
# Go to the Root directory
  - env:
      - language: cpp
  - cd ${TRAVIS_BUILD_DIR}
  - ${TRAVIS_BUILD_DIR}/NewEnv/bin/cmake CMakeLists.txt
  - make
  - make install
### install python package
language: python
  - python:       
    - "3.6"
script:    
  - pip install -r requirements.txt
  - cd python-wrapper
  - python setup.py install  
    # command to run tests
  - python setup.py test
   #
  - cd pyWDF
  - python setup.py install  

