# Travis CI  
# (C) 2017 Elena Cuoco
language: cpp
sudo: false
env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"




matrix:
  include:
  - os: linux
    env: PYTHON=3.6 CPP=11 GCC=4.8
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes]
        packages: [g++-4.8, cmake, python3.6-dev]

before_install:
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh



# Build steps
script:
# Go to the Root directory
  - ${ENV_ROOT}/bin/cmake CMakeLists.txt
  - make
  - make install
 # - cd python-wrapper
 # - sudo python$PYTHON_VERSION setup.py install
 # - python$PYTHON_VERSION setup.py test
 # - cd pyWDF
 # - sudo python$PYTHON_VERSION setup.py install


