# Travis CI  
# (C) 2017 Elena Cuoco

os:
 - linux

sudo: required

before_install:
  - sudo apt-get install libboost-dev libfftw3-dev build-essential libssl-dev libffi-dev python3 python3-dev python3-setuptools
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/deps"
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc

# Build steps
script:
# Go to the Root directory
  - export PYTHON_VERSION=export PYTHON_VERSION=`python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}".format(*version))'`
  - source ${DEPS_DIR}/environment   
  - cd ${TRAVIS_BUILD_DIR}
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/deps"
  - ${ENV_ROOT}/bin/cmake CMakeLists.txt
  - make 
  - make install
 # - cd python-wrapper
 # - sudo python$PYTHON_VERSION setup.py install
 # - python$PYTHON_VERSION setup.py test
 # - cd pyWDF
 # - sudo python$PYTHON_VERSION setup.py install

 
