# Travis CI  
# (C) 2017 Elena Cuoco


env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - GCC_VERSION=5 CPP=14 LIBCXX=On


sudo: required

before_install:
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - sudo apt-get install libboost-dev libfftw3-dev
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
compiler:
  - gcc: 5.3
  - clang: 3.7

# Build steps
script:
# Go to the Root directory
  - cd ${TRAVIS_BUILD_DIR}
  - ${TRAVIS_BUILD_DIR}/NewEnv/bin/cmake CMakeLists.txt
  - make
  - make install

#  # command to install dependencies
#  install:
#    - pip install --user -r requirements.txt
#    - cd python-wrapper
#    - python setup.py install --user
  # command to run tests
#  script: python setup.py test
  #
#  - cd ../pyWDF
#  - python setup.py install --user


### install python package
#language: python
#python:
#  - "3.6"
#install:
#  - pip install -r requirements.txt
#  - cd python-wrapper
#  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
#  - python setup.py install
# command to run tests
#  - python setup.py test
#  - cd pyWDF
#  - python setup.py install




