# Travis CI  
# (C) 2017 Elena Cuoco

 
os:
 - linux

sudo: required
before_install:
  - sudo apt-get install libfftw3-3 libgsl0ldbl libboost-all-dev
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
  
install: 
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - ./install-dependencies.sh
# Build steps
# Go to the Root directory
  - source ${DEPS_DIR}/environment   
  - cd ${TRAVIS_BUILD_DIR}
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/deps"
  - ${DEPS_DIR}/bin/cmake CMakeLists.txt  
  - make 
  - make install
   

 
