# Travis CI  
# (C) 2017 Elena Cuoco

 
os:
 - linux

sudo: required
before_install:
  - sudo apt-get install libfftw3-3 libgsl0ldbl libboost-all-dev
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - ENV_ROOT=DEPS_DIR
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-rc1.tar.gz
  - tar xfz cmake-3.8.0-rc1.tar.gz                         
  - cd cmake-3.8.0-rc1                                   
  - ./configure --prefix=${DEPS_DIR} 
  - make VERBOSE=0
  - make install                     
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd ..
  - wget http://lappweb.in2p3.fr/virgo/FrameL/libframe-8.30.tar.gz
  - tar xfz libframe-8.30.tar.gz
  - cd libframe-8.30
  - ./configure --prefix=${DEPS_DIR}
  - make VERBOSE=0
  - make install
  # Go to the Root directory  
  - cd ..
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

# Build steps
script:
  - ${DEPS_DIR}/cmake/bin/cmake CMakeLists.txt  
  - make 
  - make install
   

 
