# Travis CI  
# (C) 2017 Elena Cuoco


env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - GCC_VERSION=5 CPP=14 LIBCXX=On



sudo: required
# Enable C++ support

compiler:
  clang:
    - 3.8

  gcc:
    - 5.3
  g++:
    - 5.3


stdlib:
  - libc++
  - stdlibc++

boost:
  - 1.63.0
language: python
python:
  - "3.6"


before_install:
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - sudo apt-get install libboost-dev libfftw3-dev
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Build steps
script:
# Go to the Root directory
  - cd ${TRAVIS_BUILD_DIR}
  - cmake CMakeLists.txt
  - make
  - make install
  - pip install -r requirements.txt
  - cd python-wrapper
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - python setup.py install
# command to run tests
  - python setup.py test
  - cd pyWDF
  - python setup.py install




