# Travis CI  
# (C) 2017 Elena Cuoco

os:
 - linux
matrix:
  include:
    - python: 3.6
      env:
        global:
        - CI_NODE_TOTAL=7
        - MAKEFLAGS="-j 7"

compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang



sudo: required

before_install:
  - sudo apt-get install libboost-dev libfftw3-dev #build-essential libssl-dev libffi-dev python3 python3-dev python3-setuptools
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/deps"
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc

# Build steps
script:
# Go to the Root directory
  - export PYTHON_VERSION=export PYTHON_VERSION=`python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}".format(*version))'`
  - source ${DEPS_DIR}/environment   
  - cd ${TRAVIS_BUILD_DIR}
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/deps"
  - ${ENV_ROOT}/bin/cmake CMakeLists.txt
  - make 
  - make install
  - cd python-wrapper
  - python$PYTHON_VERSION setup.py install
  - python$PYTHON_VERSION setup.py test
  - cd pyWDF
  - python$PYTHON_VERSION setup.py install

 
