# Travis CI  
# (C) 2017 Elena Cuoco


env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - GCC_VERSION=5 CPP=11 LIBCXX=Off



sudo: required
# Enable C++ support
compiler:
  - gcc-5
  - g++-5
  - clang-3.6
std:
  - c++0x
  - gnu++0x


addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6

before_install:
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - sudo apt-get install libboost-dev libfftw3-dev
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=`echo $PATH | sed -e 's/\/usr\/local\/clang-3.5.0\/bin://'`; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.6/bin/clang 60 --slave /usr/bin/clang++ clang++ /usr/lib/llvm-3.6/bin/clang++; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/local/clang-3.5.0/bin/clang 40 --slave /usr/bin/clang++ clang++ /usr/local/clang-3.5.0/bin/clang++; fi
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Build steps
script:
# Go to the Root directory
  - cd ${TRAVIS_BUILD_DIR}
  - cmake CMakeLists.txt
  - make
  - make install
### install python package
language: python
python:
  - "3.6"
script:
  - pip install -r requirements.txt
  - cd python-wrapper
  - python setup.py install
# command to run tests
  - python setup.py test
  - cd pyWDF
  - python setup.py install




