# Travis CI
# (C) 2017 Elena Cuoco


env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - GCC_VERSION=5 CPP=11


sudo: required

before_install:
  - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
  - sudo apt-get install libboost-dev libfftw3-dev
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
compiler:
  - gcc: 5.3
  - clang: 3.8
  - cmake: 3.8

# Build steps
script:
# Go to the Root directory
  - cd ${TRAVIS_BUILD_DIR}
  - ${TRAVIS_BUILD_DIR}/NewEnv/bin/cmake CMakeLists.txt
  - make
  - make install
### install python package
after_success:
  language: python
  python:
   - "3.6"

#  # command to install dependencies
#  install:
#    - pip install --user -r requirements.txt
#    - cd python-wrapper
#    - python setup.py install --user
  # command to run tests
#  script: python setup.py test
  #
#  - cd ../pyWDF
#  - python setup.py install --user






