# Travis CI  
# (C) 2017 Elena Cuoco

env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
    - ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"


sudo: required
os: linux
language: cpp
 # Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source venv/bin/activate; fi
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh



# Build steps
script:
# Go to the Root directory
  - ${ENV_ROOT}/bin/cmake CMakeLists.txt
  - make
  - make install
 # - cd python-wrapper
 # - sudo python$PYTHON_VERSION setup.py install
 # - python$PYTHON_VERSION setup.py test
 # - cd pyWDF
 # - sudo python$PYTHON_VERSION setup.py install


