# Travis CI  
# (C) 2017 Elena Cuoco

env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
    - ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"



sudo: required

matrix:
     include:
         - os: osx
           language: generic
 # Perform the manual steps on osx to install python3 and activate venv
  before_install:
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/deps"
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc

# Build steps
script:
# Go to the Root directory
  - export PYTHON_VERSION=export PYTHON_VERSION=`python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}".format(*version))'`
  - source ${DEPS_DIR}/environment
  - cd ${TRAVIS_BUILD_DIR}
  - ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
  - ${ENV_ROOT}/bin/cmake CMakeLists.txt
  - make
  - make install
 # - cd python-wrapper
 # - sudo python$PYTHON_VERSION setup.py install
 # - python$PYTHON_VERSION setup.py test
 # - cd pyWDF
 # - sudo python$PYTHON_VERSION setup.py install


