# Travis CI  
# (C) 2017 Elena Cuoco

os:
 - linux
language: generic
python:
 - "3.6"

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       #
       - g++-4.8
       - clang
env:
  global:
    - CI_NODE_TOTAL=7
    - MAKEFLAGS="-j 7"
    - ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
    - ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"
    - export ENV_ROOT="${TRAVIS_BUILD_DIR}/NewEnv"
    - export ENV_TMP="${TRAVIS_BUILD_DIR}/tmp"


sudo: required

before_install:
  - sudo apt-get install libboost-dev libfftw3-dev
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - cd ${TRAVIS_BUILD_DIR}
  - ./install_dependencies.sh

# Enable C++ support
compiler:
  - gcc
  - clang

# Build steps
script:
# Go to the Root directory
  - cd ${TRAVIS_BUILD_DIR}
  - ${TRAVIS_BUILD_DIR}/NewEnv/bin/cmake CMakeLists.txt
  - make 
  - make install
### install python package
  - cd python-wrapper
  - python setup.py install
  - python setup.py test
  - cd pyWDF
  - python setup.py install

 
